version: '3.8'

services:
  api:
    build: .
    image: averis-api:latest
    container_name: averis-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - GCP_SA_CREDENTIALS=${GCP_SA_CREDENTIALS}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    volumes:
      - ./temp:/app/temp
